### ISSUE TITLE
Might have found a problem in extension.js or in NodeCG documentation

### ISSUE THREAD

**Issue by headwarsun** [SupportClass/lfg-sublistener#3]
Hello,

First of all thanks to the dev to have made NodeCG and all these bundles available.
I didn't manage to use lfg-sublistener bundle until I modified line 36 in file extension.js

``` javascript
if (nodecg.config.login.twitch.scope.split(' ').indexOf('channel_subscriptions') < 0) {
```

to

``` javascript
if (nodecg.config.login.twitch.scope.indexOf('channel_subscriptions') < 0) {
```

The problem is nodecg,config.login.twitch.scope should already be an array of string as it is indicated in [nodecg documentation](http://nodecg.com/starter/configuration.html), the current code assumes it should be a string of space separated permissions.

**Comment by Lange** [comment]
You're right! Mind opening a pull request?

**Comment by headwarsun** [comment]
Pull request done (I guess, not yet familiar with GitHub), by the way shouldn't the [documentation example](http://nodecg.com/starter/configuration.html) be modified as well ? Something like

``` javascript
{
    (...)
        "twitch": {
            (...)
            "scope": [
                "user_read"
            ],
            (...)
        }
    }
}
```

instead of

``` javascript
{
    (...)
        "twitch": {
            (...)
            "scope": "user_read",
            (...)
        }
    }
}
```

**Comment by Lange** [comment]
Hm actually, I think I was hasty in having you submit this PR. It looks like some other bits depend on this being a space-separated string, even though that is a bit silly.

For now, I'm going to update the docs in places where they say the scope should be a string.

**Comment by headwarsun** [comment]
I understand, nothing "a bit silly" it is just as the [Twitch-API doc](https://github.com/justintv/Twitch-API/blob/master/authentication.md#scope) says : 

> "Scopes are specified as a space separated list (...)"

Already closed my Pull request, gonna modify my nodecg config file, thanks for your answer.
