### ISSUE TITLE
NodeCG quits if IRC Ping Timeout

### ISSUE THREAD

**Issue by coolacid** [SupportClass/lfg-sublistener#7]
Currently, if there is a ping timeout for the IRC connection NodeCG will completely quit. 

```
[12:24pm] error: Ping timeout.
warn: [lfg-sublistener] DISCONNECTED:
```

Expected results are that NodeCG will continue to run, and SubListener will continue to re-attempt connections.

**Comment by Lange** [comment]
And this is with `nodecg.bundleConfig['tmi.js'].connection.reconnect` being set to `true`?

**Comment by Lange** [comment]
I just tested on my end and this doesn't appear to be the case when `nodecg.bundleConfig['tmi.js'].connection.reconnect` is `true`.
